steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/skhus-backend:$BRANCH_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/skhus-backend:$BRANCH_NAME']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'skhus-backend-$BRANCH_NAME',
    '--image', 'asia.gcr.io/$PROJECT_ID/skhus-backend:$BRANCH_NAME',
    '--region', 'asia-northeast1',
    '--memory', '1536Mi',
    '--concurrency', '4',
    '--cpu', '2',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--set-env-vars', 'GIN_MODE=release']
