steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/skhus-backend:$TAG_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/skhus-backend:$TAG_NAME']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'skhus-backend-$TAG_NAME',
    '--image', 'asia.gcr.io/$PROJECT_ID/skhus-backend:$TAG_NAME',
    '--region', 'asia-northeast1',
    '--memory', '512Mi',
    '--concurrency=1',
    '--platform', 'managed',
    '--allow-unauthenticated']
images:
  - 'asia.gcr.io/$PROJECT_ID/skhus-backend'
